apiVersion: build.knative.dev/v1alpha1
kind: BuildTemplate
metadata:
  name: kaniko
spec:
  parameters:
    - name: IMAGE
      description: The name of the image to push
    - name: DOCKERFILE
      description: Path to the Dockerfile to build.
      default: Dockerfile
    - name: BUILDCONTEXT
      description: Path to the docker build context.
      default: /workspace

  steps:
    - name: build-and-push
      image: gcr.io/kaniko-project/executor
      args:
        - --dockerfile=${DOCKERFILE}
        - --destination=${IMAGE}
        - --context=${BUILDCONTEXT}
